In [ ]:
import pandas as pd
import numpy as np

# Generate hourly temperature data for a year
date_range = pd.date_range(start='2023-01-01', end='2023-12-31 23:00:00', freq='H')
hourly_temp = 15 + 10 * np.sin(np.arange(len(date_range)) * 2 * np.pi / (365 * 24)) + np.random.randn(len(date_range)) * 3

df = pd.DataFrame({'Timestamp': date_range, 'Temperature': hourly_temp})
df.set_index('Timestamp', inplace=True)

# 1. Average daily temperature
daily_avg = df.resample('D').mean()
print("Average Daily Temperature (first 5 days):")
print(daily_avg.head())

# 2. Hottest and coldest months
monthly_avg = df.resample('M').mean()
hottest_month = monthly_avg['Temperature'].idxmax().strftime('%B')
coldest_month = monthly_avg['Temperature'].idxmin().strftime('%B')
print(f"\nHottest month: {hottest_month}")
print(f"Coldest month: {coldest_month}")

# 3. Weekly temperature trend
weekly_stats = df.resample('W').agg({'Temperature': ['min', 'mean', 'max']})
weekly_stats.columns = ['Min Temp', 'Mean Temp', 'Max Temp']
print("\nWeekly Temperature Trend (first 5 weeks):")
print(weekly_stats.head())


Average Daily Temperature (first 5 days):
            Temperature
Timestamp              
2023-01-01    15.727813
2023-01-02    15.785228
2023-01-03    15.380030
2023-01-04    15.365750
2023-01-05    16.189933

Hottest month: April
Coldest month: September

Weekly Temperature Trend (first 5 weeks):
             Min Temp  Mean Temp   Max Temp
Timestamp                                  
2023-01-01   8.000172  15.727813  21.392866
2023-01-08   6.725232  16.053211  22.959720
2023-01-15   8.533657  16.938140  25.987845
2023-01-22  10.896880  18.150462  24.331789
2023-01-29  13.618559  19.654720  27.144222


<ipython-input-1-60bb7e89e96c>:5: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  date_range = pd.date_range(start='2023-01-01', end='2023-12-31 23:00:00', freq='H')
<ipython-input-1-60bb7e89e96c>:17: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_avg = df.resample('M').mean()


In [ ]:
k = 2.3 * (10**(-12))
j = 3.4 * (10**(-11))
result = k+j
print(f'{result:.20f}')

0.00000000003630000000


In [ ]:
import numpy as np
a = np.array(4)
print(a)
a.ndim

4


0

In [ ]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
a.ndim

[1 2 3 4]


1

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2